export const ADD_NAME_FILTER = "ADD_NAME_FILTER";
export const ADD_CATEGORY_FILTER = "ADD_CATEGORY_FILTER";
export const ADD_PRICE_FILTER = "ADD_PRICE_FILTER";
export const REMOVE_FILTER = "REMOVE_FILTER";